[package]
name = "stratum-server"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
flate2.workspace = true
stratum-store = { path = "../stratum-store" }
stratum-proto = { path = "../stratum-proto" }
stratum-engine = { path = "../stratum-engine" }
stratum-control = { path = "../stratum-control" }
axum = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal", "time", "sync", "fs"] }
tokio-stream = "0.1"
bytes = "1"
serde.workspace = true
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
hmac = "0.12"
rand = "0.8"
rsa = { version = "0.9", features = ["sha1", "sha2"] }
ed25519-dalek = "3"
ureq.workspace = true
libc.workspace = true
russh = "0.63.0"
granit-parser.workspace = true

[dev-dependencies]
flate2.workspace = true
postgres.workspace = true
stratum-testkit = { path = "../stratum-testkit" }
ureq.workspace = true
