[package]
name = "stratum-testkit"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
stratum-store = { path = "../stratum-store" }
ureq.workspace = true
postgres.workspace = true
libc.workspace = true
serde_json.workspace = true
hmac = "0.12"
sha1.workspace = true
sha2.workspace = true
rsa = { version = "0.9", features = ["sha2"] }
